/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "player" CASCADE;

CREATE TABLE "player" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "ip" TEXT NOT NULL,
  "datetime" TEXT NOT NULL,
  "platform" TEXT NOT NULL);

